### ISSUE TITLE
Auth Token env variable

### ISSUE THREAD

**Issue by mcavoybn** [ForstaLabs/translation-bot#4]
The current user onboarding setup is a bit cumbersome. We should replace it with auth tokens.

**Comment by mcavoybn** [comment]
Closing -- auth tokens are created and stored automatically via the bot onboarding process now.

**Comment by rosew** [comment]
First, I love the fact that bot creation is now totally handled in the bot so people don't have to mess with anything on the forsta side first. However, I just thought of one case we may need to consider. What happens if we need to rebuild our server for one reason or another, and want to use the same bot that was created for the old server. Will we have to create a new bot or will there be a way to pull in old bots and just reset their credentials? 

(And if there is not don't necessarily do that now.. just something for us to consider and be aware of in the future. I think this is perfect for right now.)

**Comment by mcavoybn** [comment]
In general, rebuilding the server shouldnt mean we need to create a new bot user. All the bot users information is stored in a database. However there is no easy way to reuse a bot user in the case that you make a breaking change and want to reset.

I have on my list adding the ability to use an existing user during the onboarding process, and changing the current bot user via the settings menu. I also want to create a headless version of the bot which is configured via the command line and/or a 
.env file at some point. Its a low priority though.
